name: Issue created demo
on:
  issues:
    types:
      - opened
jobs:
  Describe-Issue:
    runs-on: ubuntu-latest
    steps:
      - run: echo "New issue has been created on event ${{ github.event_name }}."
